#!/usr/bin/env python
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
import jupyter_cms.extensionapp

if __name__ == '__main__':
    jupyter_cms.extensionapp.main()
